name: "Desprovisionamento de infraestrutura do cognito"
on:
  workflow_dispatch:  
  workflow_call:

env:
  TERRAFORM_DIR: terraform/cognito

jobs:
  destroi_infra:
    name: "Desprovisionamento da infra"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4.2.2

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}
      
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.3"

      - name: Terraform Init
        id: init
        run: terraform -chdir=$TERRAFORM_DIR init
        
      - name: Desprovisionando infra
        run: terraform -chdir=$TERRAFORM_DIR destroy -auto-approve
