name: Build lambda authentication
on:
    push:
      branches: [ develop ]   # Aceita push em qualquer branch
    pull_request:

env:
  PROJECT_PATH: src/AutenticacaoFunction/src/AutenticacaoFunction
  ENVIRONMENT: ${{ (github.ref_name == 'main' || github.event_name == 'pull_request') && 'prod' || 'dev' }}
jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ env.ENVIRONMENT }}
    steps:
      - name: Set outputs
        run: echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT

  build:
    uses: ./.github/workflows/build_lambda.yaml
    secrets: inherit

  cognito:
    needs: [setup, build]
    uses: ./.github/workflows/cognito.yaml
    secrets: inherit
    with:
      environment: ${{ needs.setup.outputs.environment }} 
  
  deploy_lambda:
      needs: cognito
      uses: ./.github/workflows/deploy_lambda.yaml
      secrets: inherit
      with:
        cognito_user_pool_id: ${{ needs.cognito.outputs.cognito_user_pool_id }}
        cognito_user_pool_client_id: ${{ needs.cognito.outputs.cognito_user_pool_client_id }}
