name: Build lambda authentication
on:
    push:
      branches: [ develop ]   # Aceita push em qualquer branch
    pull_request:

env:
  PROJECT_PATH: src/AutenticacaoFunction/src/AutenticacaoFunction  
jobs:

  build:
    uses: ./.github/workflows/build_lambda.yaml
    secrets: inherit

  destroi_cognito:
    needs: build
    uses: ./.github/workflows/destroi_cognito.yaml
    secrets: inherit

  cognito:
    needs: destroi_cognito
    uses: ./.github/workflows/cognito.yaml
    secrets: inherit
  
  lambda:
      needs: cognito
      uses: ./.github/workflows/lambda.yaml
      secrets: inherit
      with:
        cognito_user_pool_id: ${{ needs.cognito.outputs.cognito_user_pool_id }}
        cognito_user_pool_client_id: ${{ needs.cognito.outputs.cognito_user_pool_client_id }}
